### ISSUE TITLE
package.json 少了material-ui这项依赖

### ISSUE THREAD

**Issue by zhouxinyong** [2yuri/react-kanzhihu#1]
## package.json 少了material-ui这项依赖，npm install 后启动报错。

**Comment by jcpplus** [comment]
嗯，`Module not found`

**Comment by 2yuri** [comment]
好了，update了一下package.json， subheader是material-ui 0.15.0-alpha.1版本新增加的component。

现在直接 `npm install `就ok

**Comment by zhouxinyong** [comment]
恩恩 我手动Install的，启动后访问报错bundle.js:54912 Uncaught TypeError: getMuiTheme is not a function。

**Comment by 2yuri** [comment]
之前material-ui版本是alpha.2的，我现在degrade到0.15.0-alpha.1了，你清空下node_modules，重新 npm install.应该没问题了，我试了下。

**Comment by zhouxinyong** [comment]
确实是material-ui版本问题~
