### ISSUE TITLE
bundle.js:49653 Uncaught TypeError: getMuiTheme is not a function

### ISSUE THREAD

**Issue by SuperKieran** [2yuri/react-kanzhihu#2]
bundle.js:49653 Uncaught TypeError: getMuiTheme is not a function
按照readme报错哎

**Comment by 2yuri** [comment]
material-ui版本问题，`npm install material-ui@0.15.0-alpha.1`，安装alpha.1版本
我把package.json更新了一下，你可以`git pull` 再重新 `npm install.`
